eureka:
  instance:
    hostname: localhost
spring:
  kafka:
    bootstrap-servers: http://localhost:9092
  cloud:
    netflix:
      eureka:
        instance:
          hostname: localhost
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food-ordering
    username: postgres
    password: postgres
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    default-schema: meal_service
    schemas: meal_service
    baseline-description: "init"
    baseline-version: 1
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8090