eureka:
  instance:
    hostname: localhost

spring:
  kafka:
    retries: 5
    delivery-timeout-ms: 180000
    request-timeout-ms: 60000
    max-block-ms: 60000
    bootstrap-servers: localhost:9092
  cloud:
    netflix:
      eureka:
        instance:
          hostname: localhost
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food-ordering
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: order_service
    schemas: order_service
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

server:
  port: 8091

grpc:
  server:
    port: 9091

order:
  service:
    address: localhost
    grpc: 9090