eureka:
  instance:
    hostname: localhost
spring:
  cloud:
    netflix:
      eureka:
        instance:
          hostname: localhost
        client:
          serviceUrl:
            defaultZone: http://localhost:8761/eureka/
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food-ordering
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: restaurant_service
    schemas: restaurant_service
    baseline-on-migrate: true
    baseline-version: 1
    baseline-description: "init"
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
server:
  port: 8092
