spring:
  config:
    import: optional:configserver:http://config-service:8888
  application:
    name: MEAL-SERVICE
flyway:
  table: flyway_schema_history_meal

logging:
  level:
    com.example.mealservice.api: INFO
    com.example.mealservice.business: INFO
    root: INFO