CREATE SCHEMA IF NOT EXISTS order_service;

CREATE TABLE NEW_ORDER
(
ORDER_NUMBER VARCHAR(15) NOT NULL,
TOTAL_PRICE  NUMERIC (5,2),
STATUS      VARCHAR(40)     NOT NULL,
ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
CLIENT_ID INT NOT NULL,
RESTAURANT_ID INT NOT NULL,
PRIMARY KEY (ORDER_NUMBER)

);